language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc
    - g++
    - flex
    - bison
    - libboost1.55-all-dev
    - cmake

script:
- ./script/build.sh -debug && cd ./build && make -j10