language: cpp
compiler: gcc
os:
- linux
sudo: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - gcc-5
            - g++-5
            - flex
            - bison
            - libboost1.55-all-dev
            - cmake
install:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
script:
 -  ./script/build.sh -debug && cd ./build && make