language: generic
script:
  - ./script/build.sh -debug && cd ./build && make
sudo: false
matrix:
  include:
      os: linux
      compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - gcc-5
            - g++-5
            - flex
            - bison
            - libboost1.55-all-dev
            - cmake
      env:   
        global:
          - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5